### ISSUE TITLE
Choose a license that suits config-editor project

### ISSUE THREAD

**Issue by TheRealHoko** [TheRealHoko/config-editor#6]

**Comment by STR4Z** [comment]
Hi there, which licence should i chose ?

**Comment by TheRealHoko** [comment]
Hmmm maybe you can start looking up [here](https://choosealicense.com/)

**Comment by TheRealHoko** [comment]
travaille esclave

**Comment by STR4Z** [comment]
Hello @TheRealHoko, i think that the Apache Licence would be the best to do as we are a free project.

**Comment by STR4Z** [comment]
Hi, finally we will go for GPL as it suits better to the project needs.
